/* soapClient.c
   Generated by gSOAP 2.8.33 for slaveexecute.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.33 2016-11-22 03:04:40 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct __ns1__HelloWorldResponse *_param_1)
{	struct __ns1__HelloWorld soap_tmp___ns1__HelloWorld;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:HelloWorld";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld, "-ns1:HelloWorld", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld, "-ns1:HelloWorld", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default___ns1__HelloWorldResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SlaveExecuteCMD(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SlaveExecuteCMD *ns1__SlaveExecuteCMD, struct _ns1__SlaveExecuteCMDResponse *ns1__SlaveExecuteCMDResponse)
{	struct __ns1__SlaveExecuteCMD soap_tmp___ns1__SlaveExecuteCMD;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:SlaveExecuteCMD";
	soap_tmp___ns1__SlaveExecuteCMD.ns1__SlaveExecuteCMD = ns1__SlaveExecuteCMD;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SlaveExecuteCMD(soap, &soap_tmp___ns1__SlaveExecuteCMD);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SlaveExecuteCMD(soap, &soap_tmp___ns1__SlaveExecuteCMD, "-ns1:SlaveExecuteCMD", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SlaveExecuteCMD(soap, &soap_tmp___ns1__SlaveExecuteCMD, "-ns1:SlaveExecuteCMD", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SlaveExecuteCMDResponse)
		return soap_closesock(soap);
	soap_default__ns1__SlaveExecuteCMDResponse(soap, ns1__SlaveExecuteCMDResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__SlaveExecuteCMDResponse(soap, ns1__SlaveExecuteCMDResponse, "ns1:SlaveExecuteCMDResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReportIP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct __ns1__ReportIPResponse *_param_1)
{	struct __ns1__ReportIP soap_tmp___ns1__ReportIP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:ReportIP";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ReportIP(soap, &soap_tmp___ns1__ReportIP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReportIP(soap, &soap_tmp___ns1__ReportIP, "-ns1:ReportIP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReportIP(soap, &soap_tmp___ns1__ReportIP, "-ns1:ReportIP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default___ns1__ReportIPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ExecuteCMD(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ExecuteCMD *ns1__ExecuteCMD, struct _ns1__ExecuteCMDResponse *ns1__ExecuteCMDResponse)
{	struct __ns1__ExecuteCMD soap_tmp___ns1__ExecuteCMD;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:ExecuteCMD";
	soap_tmp___ns1__ExecuteCMD.ns1__ExecuteCMD = ns1__ExecuteCMD;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ExecuteCMD(soap, &soap_tmp___ns1__ExecuteCMD);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ExecuteCMD(soap, &soap_tmp___ns1__ExecuteCMD, "-ns1:ExecuteCMD", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ExecuteCMD(soap, &soap_tmp___ns1__ExecuteCMD, "-ns1:ExecuteCMD", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ExecuteCMDResponse)
		return soap_closesock(soap);
	soap_default__ns1__ExecuteCMDResponse(soap, ns1__ExecuteCMDResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__ExecuteCMDResponse(soap, ns1__ExecuteCMDResponse, "ns1:ExecuteCMDResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct __ns1__HelloWorldResponse_ *_param_1)
{	struct __ns1__HelloWorld_ soap_tmp___ns1__HelloWorld_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:HelloWorld";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_, "-ns1:HelloWorld", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_, "-ns1:HelloWorld", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default___ns1__HelloWorldResponse_(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SlaveExecuteCMD_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SlaveExecuteCMD *ns1__SlaveExecuteCMD, struct _ns1__SlaveExecuteCMDResponse *ns1__SlaveExecuteCMDResponse)
{	struct __ns1__SlaveExecuteCMD_ soap_tmp___ns1__SlaveExecuteCMD_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:SlaveExecuteCMD";
	soap_tmp___ns1__SlaveExecuteCMD_.ns1__SlaveExecuteCMD = ns1__SlaveExecuteCMD;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SlaveExecuteCMD_(soap, &soap_tmp___ns1__SlaveExecuteCMD_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SlaveExecuteCMD_(soap, &soap_tmp___ns1__SlaveExecuteCMD_, "-ns1:SlaveExecuteCMD", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SlaveExecuteCMD_(soap, &soap_tmp___ns1__SlaveExecuteCMD_, "-ns1:SlaveExecuteCMD", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SlaveExecuteCMDResponse)
		return soap_closesock(soap);
	soap_default__ns1__SlaveExecuteCMDResponse(soap, ns1__SlaveExecuteCMDResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__SlaveExecuteCMDResponse(soap, ns1__SlaveExecuteCMDResponse, "ns1:SlaveExecuteCMDResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReportIP_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct __ns1__ReportIPResponse_ *_param_1)
{	struct __ns1__ReportIP_ soap_tmp___ns1__ReportIP_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:ReportIP";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ReportIP_(soap, &soap_tmp___ns1__ReportIP_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReportIP_(soap, &soap_tmp___ns1__ReportIP_, "-ns1:ReportIP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReportIP_(soap, &soap_tmp___ns1__ReportIP_, "-ns1:ReportIP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default___ns1__ReportIPResponse_(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ExecuteCMD_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ExecuteCMD *ns1__ExecuteCMD, struct _ns1__ExecuteCMDResponse *ns1__ExecuteCMDResponse)
{	struct __ns1__ExecuteCMD_ soap_tmp___ns1__ExecuteCMD_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap11Endpoint/ http://192.168.131.97:8080/TomcatSocket/services/mainservice.mainserviceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:ExecuteCMD";
	soap_tmp___ns1__ExecuteCMD_.ns1__ExecuteCMD = ns1__ExecuteCMD;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ExecuteCMD_(soap, &soap_tmp___ns1__ExecuteCMD_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ExecuteCMD_(soap, &soap_tmp___ns1__ExecuteCMD_, "-ns1:ExecuteCMD", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ExecuteCMD_(soap, &soap_tmp___ns1__ExecuteCMD_, "-ns1:ExecuteCMD", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ExecuteCMDResponse)
		return soap_closesock(soap);
	soap_default__ns1__ExecuteCMDResponse(soap, ns1__ExecuteCMDResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__ExecuteCMDResponse(soap, ns1__ExecuteCMDResponse, "ns1:ExecuteCMDResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
